### ISSUE TITLE
Suggestion: Make ied interactive

### ISSUE THREAD

**Issue by dthree** [alexanderGugel/ied#1]
Looks great, btw! Gave it a :+1: 

Just a suggestion, you can shoot this down if you want:

[Vorpal](https://github.com/dthree/vorpal) is a recent CLI framework which would make `ied` into an interactive app. With this, you can run it straight from the terminal and have it execute a single command and then exit as it does now; or you can have the app remain alive in an interactive prompt, sort of giving it its own namespace. In this, you could do some awesome things such as providing tabbed auto-completion of available packages. Here's [some examples](https://github.com/mischah/itunes-remote) of [what you can do](https://github.com/dthree/wat) with Vorpal. If you have any questions, just let me know!

**Comment by alexanderGugel** [comment]
Looks super cool! Will look into it!

**Comment by dthree** [comment]
:+1: wish you the best!

**Comment by alexanderGugel** [comment]
Tried it, but introduces tons of new dependencies. Don't like that.
