### ISSUE TITLE
Support .npmrc configuration

### ISSUE THREAD

**Issue by baldmountain** [alexanderGugel/ied#107]
It would be good if ied would read and use options from the user's or project's .npmrc file. Usually there is more in there than just a registry. We use artifactory and authentication so for us ied would need to be able to authenticate to artifactory in the same way npm does.

This is probably related to the issue of supporting private repositories. Issue 103.

**Comment by alexanderGugel** [comment]
Using an existing `.npmrc` file as configuration is not planned. This adds additional complexity and might in fact be confusing when we still have an `iedrc` or other ied-specific config file.

**Comment by alexanderGugel** [comment]
That being said, we're not planning on using `ini` style config files, but plain old JSON.
