### ISSUE TITLE
--save-dev also copy "dependencies" into "devDependencies"

### ISSUE THREAD

**Issue by zhuangya** [alexanderGugel/ied#12]
for [ied](https://github.com/alexanderGugel/ied) repo it self:

```
16:57:34 nos:~/Documents/Projects/ied 9 (master u=)
~> ied install --save-dev debug
16:57:51 nos:~/Documents/Projects/ied 9 (master * u=)
~> gd
diff --git a/package.json b/package.json
index fa0aa17..507a5b7 100644
--- a/package.json
+++ b/package.json
@@ -19,11 +19,22 @@
     "tar-fs": "^1.8.1"
   },
   "devDependencies": {
-    "mocha": "^2.3.3",
+    "mocha": "^2.3.4",
     "mock-fs": "^3.4.0",
-    "mockmock": "0.0.5",
+    "mockmock": "^0.0.5",
     "proxyquire": "^1.7.3",
-    "standard": "^5.3.1"
+    "standard": "^5.3.1",
+    "archy": "^1.0.0",
+    "async": "^1.5.0",
+    "easy-table": "^1.0.0",
+    "gunzip-maybe": "^1.2.1",
+    "init-package-json": "^1.9.1",
+    "minimist": "^1.2.0",
+    "mkdirp": "^0.5.1",
+    "node-uuid": "^1.4.7",
+    "object-assign": "^3.0.0",
+    "semver": "^5.0.3",
+    "tar-fs": "^1.8.1"
   },
   "scripts": {
     "test": "mocha && standard",
@@ -44,4 +55,4 @@
     "example": "example",
     "test": "test"
   }
-}
+}
\ No newline at end of file
```

**Comment by zhuangya** [comment]
i only expected to save `debug` of coures

**Comment by alexanderGugel** [comment]
Yeah, had a look into it. This is actually not a bug, but more or less the intended behaviour, which might be confusing.... and I'm open to changes here..

* `ied install` installs all dependencies and devDependencies from `package.json`
* `ied install some-package` installs **only** some-package
* `ied install some-package --save` installs **only** some-package and saves it under `dependencies`
* `ied install some-package --save-dev` installs **only** some-package and saves it under `devDependencies`
* `ied install --save` installs all dependencies and devDependencies from `package.json` and saves them under `dependencies`
* `ied install --save-dev` installs all dependencies and devDependencies from `package.json` and saves them under `devDependencies`

etc.

Confusing cases:
* `ied install --save-dev some-package` installs all dependencies and devDependencies from `package.json` and saves them under `devDependencies`, **`some-package` is being ignored and is not being installed**

etc.

To put it in a nutshell **the order matters**. `ied install debug --save-dev` does what you would expect.

**Comment by zhuangya** [comment]
> To put it in a nutshell the order matters. ied install debug --save-dev does what you would expect.

maybe the option order should matter, or should not

but can you write this in document?

it's pretty confusing to many people i think

**Comment by sebinsua** [comment]
Can we make the behaviour of the basic commands as similar to `npm`s behaviour as possible?

If you need a rationalisation, mine is that `ied [command] [--modifier] [subject(s)]` makes more sense as it is more obvious that the modifier (e.g. `--save-dev`) is upon the command (e.g. `install`). Basically, it should be this way for the same reason you don't `ied [subject(s)] [command]` (e.g. `ied debug install`).

**Comment by mstade** [comment]
It's confusing that option order should matter, most reasonably friendly CLI tooling doesn't require this. These cases should be interchangeable:

```sh
ied install --save foo
ied install foo --save
```

The `--save` option is "tied" to the `install` command, not the argument `foo`. At least, that's how I'm used to thinking about the UX of CLI tooling.

**Comment by alexanderGugel** [comment]
This has been fixed.
