### ISSUE TITLE
unhandled "socket hang up" error

### ISSUE THREAD

**Issue by wmhilton** [alexanderGugel/ied#127]
I'm trying to make the switch from v1 to v2 of ied. I experienced one regression with the 'asynquence-contrib' package that turned out to be my fault more or less. But here's a possible bug:

```
: /opt/node-v5.2.0-linux-x64/lib/node_modules/ied/node_modules/rxjs/Observer.js:5
: error: function (err) { throw err; },
: ^
:
: Error: socket hang up
: at createHangUpError (_http_client.js:210:15)
: at TLSSocket.socketCloseListener (_http_client.js:242:23)
: at emitOne (events.js:83:20)
: at TLSSocket.emit (events.js:170:7)
: at TCP._onclose (net.js:470:12)
```

Letting one little socket error abort the whole thing probably isn't ideal. Maybe it could retry once or twice?

**Comment by alexanderGugel** [comment]
It's currently supposed to retry 5 times, unless there is a bug. Looking into it.

**Comment by wmhilton** [comment]
It happened twice in a row... but that's all the evidence I've got. I'll try harder to reproduce it. I've been having all sorts of trouble today, with apt and npm as well. Maybe just bad luck.

**Comment by mgcrea** [comment]
Could not reproduce it, probably a network error. Please feel free to reopen if you can reproduce it.

Also use `NODE_ENV=development ied i` to get a proper stack trace next time.
