### ISSUE TITLE
cross-device link not permitted

### ISSUE THREAD

**Issue by danielb2** [alexanderGugel/ied#129]
* **Version**: 2.0.4
* **Platform**: Darwin nero.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

``` bash
[/n/l/u/h/d/w/purdy.js]$ ied install
🕕  22.22% resolving hoek@2.x.x/Users/daniel/.nvm/versions/node/v4.4.5/lib/node_modules/ied/node_modules/rxjs/Observer.js:5
    error: function (err) { throw err; },
                            ^

Error: EXDEV: cross-device link not permitted, rename '/Users/daniel/.ied_cache/.tmp/d8c27b0c-41be-44c4-8e23-6f0d75a00047' -> '/net/luffy/usr/home/daniel/work/purdy.js/node_modules/5199a3ddcd0c1efe23bc08c1b027b06176e0c64f/package'
    at Error (native)
[daniel@nero]--(21:37:21)
```

The files are on an NFS mount.  ( /net/luffy )

**Comment by alexanderGugel** [comment]
The caching directory needs to be on the same device. You can configure ied to use a different caching directory (which is on the same device) by setting the `IED_CACHE_DIR` environment variable.

See https://github.com/alexanderGugel/ied/blob/master/src/config.js#L29
