### ISSUE TITLE
Support for `npm link` functionality

### ISSUE THREAD

**Issue by jmandzik** [alexanderGugel/ied#13]
For people that work with private modules, ssh/https (covered in #7 ) and `npm link` are critical to the work flow.  Please consider adding sym-linking functionality to avoid having to commit/push/install for every change when co-developing modules.  Thanks!

**Comment by alexanderGugel** [comment]
Added in 60456f48aba4557b5770c6ded4bfc5724ef68068
Might need some more work to cover some edge cases, but works for now.

* `ied link` to link the current package globally
* `ied link some-package` to link into your current repo
* `ied unlink` to unlink your current package globally (run in the repo to be unlinked)
* `ied unlink some-package` to unlink `some-package` from your current project's node_modules directory

API is likely to change in the future.

**Comment by jmandzik** [comment]
Just test drove it.  Works great!

**Comment by alexanderGugel** [comment]
Awesome! There are probably some weird edge cases in there and error handling should be better, but we're getting there.
