### ISSUE TITLE
Install same lib again but different versions doesn't work

### ISSUE THREAD

**Issue by PeterDaveHello** [alexanderGugel/ied#130]
* **Version**: 2.0.4
* **Platform**: Linux work 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 

npm behavior:
`npm install jquery@3` -> node_modules/jquery = jquery@3.0.0
then
`npm install jquery@2` -> node_modules/jquery = jquery@2.2.4

ied behavior:
`ied install jquery@3` -> node_modules/jquery = jquery@3.0.0
then
`ied install jquery@2` -> node_modules/jquery = jquery@3.0.0 (doesn't change)

The installed jquery in node_modules/jquery didn't be changed since the first/clean install, is this a bug? Thanks!

**Comment by alexanderGugel** [comment]
This is kind of by design. Problem is in the local resolve mechanism:

https://github.com/alexanderGugel/ied/blob/master/src/install.js#L69

**Comment by mgcrea** [comment]
Just fixed this in a375f38, I've only added semver check for explicit install to minimize the performance hit & since I'm not sure it should be needed otherwise.

**Comment by PeterDaveHello** [comment]
Still not work for me on v2.0.5. (BTW, v2.0.5 version tag is missing in git repo)

**Comment by PeterDaveHello** [comment]
Thanks, will this be shipped on a new version soon? Just asking, thanks.

**Comment by alexanderGugel** [comment]
Yup, this will be included in the next version.

**Comment by PeterDaveHello** [comment]
Okay, thanks.
