### ISSUE TITLE
Why ied?

### ISSUE THREAD

**Issue by KraigWalker** [alexanderGugel/ied#14]
I keep thinking about improvised explosive devices...

**Comment by spicydonuts** [comment]
Same, haha.  The name is probably fine if you can come up with an actual meaning to put in the FAQ, but currently it just says "it's easy to type", so the only thing my brain can substitute is the existing definition. : ]

**Comment by dthree** [comment]
More discussion here:

https://news.ycombinator.com/item?id=10571065

**Comment by bucaran** [comment]
It would have been more useful to help make `npm` faster instead of creating another divergence.

**Comment by alexanderGugel** [comment]
Locking. This doesn't lead anywhere. I answered all questions concerning the extremely bad name in the HN article above. I'm not a native speaker. I don't have any military experience and I frankly **simply** haven't heard of IEDs before. At least it didn't appear to me that the first thing one thinks of when hearing those three letters are wounded, dead soldiers.

In fact ied was originally called mpm, but I thought that was a confusing bad name..... boy have I been wrong....

It wasn't my intention to name this package manager after a bomb, nor did I intend to offend anyone.

At the same time, repeating what has been said before doesn't help anyone. If you have a better name, please let me know (email me at [myfirstname].[mylastname]@gmail.com). This project is very likely to be renamed, I simply haven't decided on a better name yet.

@bucaran I deleted your comment. It's offensive and frankly completely useless.
