### ISSUE TITLE
Are there plans to integrate a registry server into ied?

### ISSUE THREAD

**Issue by zjiekai** [alexanderGugel/ied#141]
Thank you for the excellent ied.  I'm wondering if there are plans to have ied work like a private registry?

**Comment by alexanderGugel** [comment]
No, but I'm working on a separate registry server. This will take anywhere between 3 - 5 months to be released. ied itself should purely be a client side package manager.

I appreciate the feedback and will keep this issue open to keep post a link once I have the first version in a stable state.

Thanks!

**Comment by wmhilton** [comment]
Really?! That is really interesting. I'm currently running a fork of local-npm and have been keeping an eye on npm-ipfs. What in particular are you planning to do better/different than the existing repository servers?

**Comment by alexanderGugel** [comment]
Closing for now. I started working on a private registry server. It's here: https://github.com/alexanderGugel/nerva

Let's continue the discussion there if you're interested.
