### ISSUE TITLE
How to skip installation of devDependencies?

### ISSUE THREAD

**Issue by juodumas** [alexanderGugel/ied#150]
* **Version**: 2.0.5

First of `ied` is amazingly fast and the speed makes it a pleasure to use!

Any plans to bring back support for `--only=prod` or `NODE_ENV=production`? The readme mentions **Arbitrary package groups** but looks like it's not implemented.

**Comment by mgcrea** [comment]
I'd rather use the `--production` flag from npm.

> With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.

**Comment by alexanderGugel** [comment]
@mgcrea Agreed. Added in #157
