### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by alexanderGugel** [alexanderGugel/ied#16]
We need more (as in "any").

Having tests makes you look like an adult.

**Comment by jmandzik** [comment]
I'd like to help!  Do you have a preferred test runner/assertion/coverage library?

**Comment by alexanderGugel** [comment]
Awesome!!! Currently the few tests we have are written in Mocha + Node's [assert](https://nodejs.org/api/assert.html). I'm open to other libraries!

I've also worked with [tap](https://www.npmjs.org/package/tap) and [tape](https://www.npmjs.org/package/tap) before and they also seem like a reasonable choices.

**Comment by alexanderGugel** [comment]
Done.
