### ISSUE TITLE
Support --no-optional flag

### ISSUE THREAD

**Issue by jmandzik** [alexanderGugel/ied#17]
Useful for when npm modules have optional dependencies you don't want or don't work on your platform.    For example, `ldapjs` had optional dependencies on some dtrace libraries that don't work on OSX and slow down installs.  Being able to skip them like I can with npm would be badass.

**Comment by alexanderGugel** [comment]
This is something that we won't implement anytime soon. In understand that this is useful in certain scenarios though.
