### ISSUE TITLE
EXDEV issue with Docker

### ISSUE THREAD

**Issue by henryruhs** [alexanderGugel/ied#177]
- **Version**: 2.3.3
- **Platform**: Ubuntu 16.04 with Docker
- **Subsystem**: Nodejs 4.2.6

Hello,

there are still issues with EXDEV inside Docker containers - mentioned in the last comment of #4

```
root@1728f869732a:/var/www/html# ied install
/usr/local/lib/node_modules/ied/node_modules/rxjs/Subscriber.js:227
            throw err;
            ^

Error: EXDEV: cross-device link not permitted, rename '/root/.ied_cache/.tmp/8c4882a5-3094-4be3-adc6-52224e98db72' -> '/var/www/html/node_modules/a7b8e2d0fb35b5a50f4af986fc112749ebc96f3d/package'
    at Error (native)
```

Current workaround:

<pre>IED_CACHE_DIR=.tmp ied install</pre>

**Comment by alexanderGugel** [comment]
Not sure if that's really temporal TBH....

I'm not sure what would be a sensible default for this caching directory. We would somehow have to detect that we're on the same device. Not sure if there is a straightforward way to do it, but any PR is welcome.
