### ISSUE TITLE
Global install fail

### ISSUE THREAD

**Issue by oligot** [alexanderGugel/ied#25]
Hi,

I tried to install ied with npm
 > npm i -g ied

but it failed

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "ied"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /usr/local/lib/node_modules/ied/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ied/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

Downloading the tarball (http://registry.npmjs.org/ied/-/ied-0.2.0.tgz) pointed by
 > npm info ied

and uncompressing it result in a single folder named _package_ with a single file _package.json_
 > tree package

package
└── package.json

0 directories, 1 file

It looks like there are missing files...

**Comment by pvledoux** [comment]
Same problem here, node 5.0 on OSX 10.11.1

**Comment by simplyianm** [comment]
You need to do `npm install -g ied@0.1.1`. For some reason there's a bad module uploaded at `0.2.0`.

**Comment by alexanderGugel** [comment]
Something went terribly, terribly wrong. I don't know what. v0.2.1 has been published.

I'm sorry.

**Comment by oligot** [comment]
No problem.
The installation works now :smirk:
