### ISSUE TITLE
IED behind a proxy

### ISSUE THREAD

**Issue by faceleg** [alexanderGugel/ied#33]
How can I use IED behind a corporate proxy?

I've tried:

```
ied config set http-proxy <my proxy>
```

**Comment by alexanderGugel** [comment]
Currently not supported. Will look into it. Any help is welcome.

Thanks for this feature request!

**Comment by faceleg** [comment]
No problem. If you could provide some pointers on how you would like this implemented and where to start in the code, anyone reading this may have enough to get started with the PR

**Comment by alexanderGugel** [comment]
@faceleg Please let me know if that works for you (see commit message for usage).

**Comment by alexanderGugel** [comment]
There is no central config file. Configuration is being managed via environment variables.

**Comment by faceleg** [comment]
Thanks @alexanderGugel! I'll try it on monday when I'm back behind the lovely proxy
