### ISSUE TITLE
Suggestion: temporarily defer to npm executable to cover gaps in functionality

### ISSUE THREAD

**Issue by davidmarkclements** [alexanderGugel/ied#34]
For instance, at the moment `ied` doesn't support installs from gtihub.
Granted listing deps from gh isn't an ideal approach, but people do it, lots (particularly if you've got a PR waiting for merge, but you need your fix now)

So we stub some code for recognizing a GH dep and then pass it to npm if/until ied supports it, e.g.

pseudo-ish code:
```js
var spawn = require('child_process').spawn
if (gh(dep)) {
  spawn('npm', ['install', dep])
   .on('end', next)
   .on('error', fail)
   .pipe(process.stdout)
}
```

Maybe create small module for handling  "npm fallthrough"

**Comment by alexanderGugel** [comment]
This would ruin performance and mess up the current architecture.
