### ISSUE TITLE
Why not working on npm ?

### ISSUE THREAD

**Issue by gabrielstuff** [alexanderGugel/ied#39]
Hi !
This looks like a great idea to want npm to be faster and easier to use.
I was wondering why as you look like you have great skills, you did not offer your time and devote your idea to the npm project ?

What are the technical challenge that forced you to start from scratch ?
Any ideologies pushed you to do so ?

Thanks,

G

**Comment by alexanderGugel** [comment]
Because it's fun.

**Comment by gabrielstuff** [comment]
ok got your point.
