### ISSUE TITLE
The "type" argument in fs.symlink

### ISSUE THREAD

**Issue by fatfisz** [alexanderGugel/ied#41]
This argument seems to be only respected on Windows, but it is currently not set correctly - it should be `'dir'`. So is there any reason for the current behavior?

I suggest the `type` argument is removed from `forceSymlink` altogether and replaced with `'dir'` where it is used.

**Comment by Hypercubed** [comment]
Actually I think you need to use 'junction' to avoid the permissions issue on windows. but to do so the paths must be absolute.

**Comment by fatfisz** [comment]
I've just tested this in `cmd` and it worked without problem, will read about this a bit more.

This should also solve #35. Also the absolute paths should not a problem in this case so everything should work out.

**Comment by fatfisz** [comment]
Ok, there's a serious problem with that: even changing the main project directory name will invalidate all of the junctions.
I think that's too big of a trade-off, because there won't be a way to warn Windows users when such a thing happens, whereas in the worst case of the symbolic link scenario they will be able to get an informative message.
Also, a new command would have to be made that regenerates all of the junctions, and it would only be useful for Windows users.

What do you think @alexanderGugel?

**Comment by Hypercubed** [comment]
I spent a long time today playing with this.  I could not get ide to run without admin.  You might have better luck.  Take a look at  this: https://github.com/npm/npm/blob/master/lib/utils/link.js

**Comment by fatfisz** [comment]
It seems that they also use junctions. Anyway, I'm looking into utilizing powershell for creating symlinks painlessly.

**Comment by alexanderGugel** [comment]
:+1:

**Comment by Hypercubed** [comment]
Yeah, from what I see `ied` (`nom`?) is much more symlink heavy.  `junction` links my be a bad idea.  Do you think using power shell will get around the need for admin?

**Comment by fatfisz** [comment]
I'm closing this, as it has been inactive for quite some time. I'm really sorry I didn't help with this as I promised.

**Comment by zkochan** [comment]
@fatfisz have you tried [pnpm](https://github.com/pnpm/pnpm). It uses a symlinked node_modules as `ied` and supports Windows fine (uses junctions on Windows)
