### ISSUE TITLE
Would not work on OSX with multiple drive ( at least by default )

### ISSUE THREAD

**Issue by temsa** [alexanderGugel/ied#5]
# Here's the error : 
```
[====                          ] 11.51%/usr/local/lib/node_modules/ied/lib/install_cmd.js:63
        if (err) throw err
                 ^

Error: EXDEV: cross-device link not permitted, rename '/var/folders/yn/rs_xqqsn3vv8ftktwl_1l0_w0000gn/T/7ec9f2a7-4722-4ddf-9717-28bb2e7c8196' -> '/Volumes/Macintosh HD 2/dev/prs/emoji/node_modules/7d3b63a17887e9e2c2bf55dbd3318fe34a39d1e7'
    at Error (native)
```

# Reproduce :

1. install using nvm, node 0.12, and fish on macosx using `npm i -g ied`
2. go to any complex node project directory ( not tried on a trivial one, but tried on 3 complex node projects )
3. do `rm -rf node_modules`
4. do `ied i`
5. get this kind of error every time

BTW, it was really fast to get to this error, ied seems a great idea besides this bug

**Comment by alexanderGugel** [comment]
Thanks for reporting! Looks like a duplicate to #4 to me. This is a known issue and will be fixed soon. Feel free to reopen.
