### ISSUE TITLE
reinstall error

### ISSUE THREAD

**Issue by aaronshaf** [alexanderGugel/ied#59]
```
ied install
rm -rf node_modules
ied install
```

```Error: Cannot find module '/Users/me/workspace/lib/node_modules/.tmp/beb952e7-ad2e-4da1-9378-61b6547389ed/package.json'```

**Comment by just-boris** [comment]
Try to clean cache. By default it is located as `~/ied-cache`. In latest version package structure has been changed and previously cached items are invalid now

**Comment by just-boris** [comment]
@aaronshaf found an issue in the code. Could you please try to check it again with my fix from #60?

**Comment by aaronshaf** [comment]
Thanks, I think that fixed it.
