### ISSUE TITLE
TypeError: Cannot read property 'dist' of null (pkg.dist.shasum)

### ISSUE THREAD

**Issue by mplewis** [alexanderGugel/ied#6]
Hello! I tried installing a package's dependencies with ied and hit the following error:

```
$ ied install
  debug('expose %s in %s', pkg.dist.shasum, dir)
                              ^

TypeError: Cannot read property 'dist' of null
    at expose (/usr/local/lib/node_modules/ied/lib/expose.js:42:31)
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:355:9)
    at Object.map (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:337:20)
    at expose (/usr/local/lib/node_modules/ied/lib/expose.js:37:11)
    at fn (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:741:34)
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:1208:16
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:701:43
```

I can post the package.json if necessary.

**Comment by alexanderGugel** [comment]
uhhhh. Yeah the dependency in question that you're trying to install would be super useful. Are you using the official npm registry?

ied uses the shasum exposed by the registry to verify that we got the correct dependency.

Usually the package.json file exposed by the npm registry has a `dist.shasum`...

**Comment by chaconnewu** [comment]
I received the exact same error on different projects when using 'ied install'. But if after the error, ran 

$ ied install

again, it will befine.

**Comment by joshuataylor** [comment]
Yeah it happens randomly, maybe a race condition?

**Comment by mplewis** [comment]
Here are the dependencies listed in my package.json:
```
{
  ...
  "dependencies": {
    "handlebars": "^3.0.3",
    "metalsmith": "^2.0.1",
    "metalsmith-autotoc": "git+https://git@github.com/mplewis/metalsmith-autotoc.git",
    "metalsmith-ignore": "^0.1.2",
    "metalsmith-in-place": "^1.3.1",
    "metalsmith-layouts": "^1.4.0",
    "metalsmith-markdown": "^0.2.1",
    "metalsmith-paths": "^2.1.1",
    "metalsmith-permalinks": "^0.4.0",
    "metalsmith-register-helpers": "^0.1.2",
    "metalsmith-register-partials": "^1.0.2",
    "metalsmith-stylus": "^1.0.0",
    "string": "^3.3.1"
  },
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-add": "0.0.2",
    "gulp-gh-pages": "^0.5.2",
    "js-yaml": "^3.3.1",
    "metalsmith-serve": "0.0.3",
    "metalsmith-watch": "^1.0.1",
    "pluralize": "^1.1.4",
    "rimraf": "^2.4.3"
  }
}
```

**Comment by josephfrazier** [comment]
I also experienced this error using ied@0.0.5 to install https://github.com/feross/webtorrent/commit/69fca75d45a5e4ccbb72cba6f961888d3dee95d2 under node v4.2.2. Here's my shell session: https://gist.github.com/josephfrazier/d32949736bf3dd89ed60

**Comment by spicydonuts** [comment]
I'm experiencing this as well.  Also node 4.2.2 and ied 0.0.5.  I can list my deps if you want, but I don't have any in common with @mplewis (react, babel, webpack, css-modules, etc)

**Comment by danii1** [comment]
Hit the same error when installing deps for https://github.com/rkusa/koa-passport-example

```
ome/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/lib/expose.js:42
  debug('expose %s in %s', pkg.dist.shasum, dir)
                              ^

TypeError: Cannot read property 'dist' of undefined
    at expose (/home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/lib/expose.js:42:31)
    at /home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:337:20)
    at expose (/home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/lib/expose.js:37:11)
    at fn (/home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:741:34)
    at /home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:1208:16
    at /home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
    at /home/daniil/.nvm/versions/node/v4.2.1/lib/node_modules/ied/node_modules/async/lib/async.js:701:43

```

**Comment by alexanderGugel** [comment]
The issue is that currently only "normal" installs from the npm registry are supported. Support for private modules, tarballs and git repos is in the works though.

**Comment by echernyavskiy** [comment]
@alexanderGugel trying ied out with a package.json that contains only regular npm dependencies - same story. Here's the stack trace:

    > node --stack-trace-limit=1000 /home/echernyavskiy/.nvm/versions/node/v0.12.7/bin/ied i
    [===========                   ] 34.64%
    /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/lib/expose.js:47
      debug('expose %s in %s', pkg.dist.shasum, dir)
                                  ^
    TypeError: Cannot read property 'dist' of undefined
        at expose (/home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/lib/expose.js:47:31)
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:356:13
        at async.forEachOf.async.eachOf (/home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:233:13)
        at _asyncMap (/home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:355:9)
        at Object.map (/home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:337:20)
        at expose (/home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/lib/expose.js:42:11)
        at fn (/home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:741:34)
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:1208:16
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:701:43
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:167:37
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:1204:30
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:52:16
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:361:13
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:52:16
        at done (/home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:246:17)
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:44:16
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:358:17
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/lib/install_cmd.js:49:11
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:52:16
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:1204:30
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/lib/install.js:107:7
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:721:13
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:52:16
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:269:32
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:44:16
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:718:17
        at /home/echernyavskiy/.nvm/versions/node/v0.12.7/lib/node_modules/ied/node_modules/async/lib/async.js:167:37
        at FSReqWrap.oncomplete (fs.js:95:15)

Does this provide any clue at all?

**Comment by alexanderGugel** [comment]
This no longer seems to be an issue.
