### ISSUE TITLE
Cannot find package.json error

### ISSUE THREAD

**Issue by rstacruz** [alexanderGugel/ied#63]
I'm getting this error on ied@0.4.0. Wish I can help debug, but I don't know where to start looking.

```
→ rm -rf node_modules
→  ied i
[=========================     ] 80.98%/Users/rsc/.nvm/versions/node/v4.1.0/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                 ^

Error: Cannot find module '/Users/rsc/Projects/.../node_modules/.tmp/5bba49cf-1574-48bc-96f8-40c2e8d0782e/package.json'
   at readPackage (/Users/rsc/.nvm/versions/node/v4.1.0/lib/node_modules/ied/lib/install.js:38:11)
    at fn (/Users/rsc/.nvm/versions/node/v4.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:746:34)
    at /Users/rsc/.nvm/versions/node/v4.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:1213:16
    at /Users/rsc/.nvm/versions/node/v4.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
```

That folder has these:

```
→ cd node_modules/.tmp/5bba49cf-1574-48bc-96f8-40c2e8d0782e

→  grep -E 'name|version' package/package.json
  "name": "babel-register",
  "version": "6.4.3",

→  find .
./node_modules
./node_modules/babel-register
./package
./package/lib
./package/lib/browser.js
./package/lib/cache.js
./package/lib/node.js
./package/package.json
./package/README.md
./package/src
./package/src/browser.js
./package/src/cache.js
./package/src/node.js
```

**Comment by just-boris** [comment]
it seems like a duplicate of this #59. Also I have a possible fix in the #60. 

@rstacruz could you please try to install my patched version and check it again?

**Comment by rstacruz** [comment]
How can I do that/

**Comment by just-boris** [comment]
```bash
npm install -g ied@just-boris/ied#patch-1
```

**Comment by rstacruz** [comment]
Neat! I'm getting this error now, but I'm sure it's a totally different issue:

```
[==============================] 97.93%/Users/rsc/.nvm/versions/node/v4.1.0/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                 ^

Error: No satisfying target found for esprima-fb@~3001.0001.0000-dev-harmony-fb
```

**Comment by just-boris** [comment]
Yes, this probably an another issue with semver.
Btw, `semver` says that your package version is invalid. Use this instead: `3001.1.0-dev-harmony-fb`

**Comment by rstacruz** [comment]
gotcha... but this is a dependency of another dependency, and I've no idea which one it may be.

**Comment by yesvods** [comment]
@rstacruz get the same problem, how do you solve that?

**Comment by rstacruz** [comment]
Nothing special in pnpm about this... Semver.maxSatisfies() handles that
version just fine.

**Comment by rstacruz** [comment]
Oops, well, in ied... Boris solved it with his patch.

For what it's worth, Esprima-FB is now deprecated. Esprima (upstream)
already supports es6 constructs.

**Comment by yesvods** [comment]
I've used Boris's patch.In order to make ide work.But I have to install babel-core by hand because ide only install 5.x version of babel-core,which I declare 6.x in package.json.
