### ISSUE TITLE
Permission denied on newly installed webpack binary in `.bin`

### ISSUE THREAD

**Issue by iamdanfox** [alexanderGugel/ied#75]
## Repro

1. Check out a repo with a dependency that includes a binary (e.g. [iamdanfox/redux-experiment][1] which depends on webpack)
2. Ensure ied cache is empty: `rm -rf ~/.ied_cache`
3. Run `ied install`
4. Run `./node_modules/.bin/webpack`

**Expected:** webpack runs and exits cleanly (verified behaviour for npm 2.14.4)
**Actual:** `zsh: permission denied: ./node_modules/.bin/webpack`

Permissions listings on my system:

```bash
$ ls -l node_modules/.bin 
total 16
lrwxr-xr-x  1 danfox  25 Jan 26 22:01 cake -> ../coffee-script/bin/cake
lrwxr-xr-x  1 danfox  27 Jan 26 22:01 coffee -> ../coffee-script/bin/coffee
lrwxr-xr-x  1 danfox  19 Jan 26 22:02 gulp -> ../gulp/bin/gulp.js
lrwxr-xr-x  1 danfox  25 Jan 26 22:02 webpack -> ../webpack/bin/webpack.js

$ ls -l node_modules/webpack/bin 
total 28
-rw-r--r-- 1 danfox  2533 Jan 23 12:48 config-optimist.js
-rw-r--r-- 1 danfox 15110 Jan 23 12:48 convert-argv.js
-rwxr-xr-x 1 danfox  5580 Jan 23 12:48 webpack.js
```

```bash
$ ls -l node_modules/.bin
total 16
lrwxr-xr-x   1 danfox    52 Jan 26 22:03 cake -> ../4c19bfd692246e95dcadad6bbc6f42ec0f2690fa/bin/cake
lrwxr-xr-x   1 danfox    54 Jan 26 22:03 coffee -> ../4c19bfd692246e95dcadad6bbc6f42ec0f2690fa/bin/coffee
lrwxr-xr-x   1 danfox    55 Jan 26 22:03 gulp -> ../a7ccee77cf203962af487703a759823d1c392cbe/bin/gulp.js
lrwxr-xr-x   1 danfox    58 Jan 26 22:03 webpack -> ../4815d10612ee2418280189fdcc53faddfd1c9e7f/bin/webpack.js

$ ls -l node_modules/4815d10612ee2418280189fdcc53faddfd1c9e7f/bin 
total 28
-rw-r--r--  1 danfox  2533 Jan 23 12:48 config-optimist.js
-rw-r--r--  1 danfox 15110 Jan 23 12:48 convert-argv.js
-rw-r--r--  1 danfox  5580 Jan 23 12:48 webpack.js
```

## System:

OSX 10.11.2
Node v0.10.31
ied version 0.4.3
npm version 2.14.4
zsh

[1]: https://github.com/iamdanfox/redux-experiment/tree/2eff4643a730892c0cc71abf0fa9bac724158e17

**Comment by just-boris** [comment]
Confirm the issue.

@alexanderGugel did it work earlier?

If not, I can fix it. We need to implicitly change chmod to executable. NPM does it [here](https://github.com/npm/npm/blob/master/lib/build.js#L205), I can add this logic here: https://github.com/alexanderGugel/ied/blob/master/lib%2Fexpose.js#L35

**Comment by rstacruz** [comment]
adding the chmod sounds right to me.

**Comment by alexanderGugel** [comment]
Yes, we need this.

**Comment by alexanderGugel** [comment]
Should be fixed. Let me know if you run into any other issues! Thanks!

**Comment by iamdanfox** [comment]
Awesome, that was impressively quick!
