### ISSUE TITLE
optionalDependencies are not installed

### ISSUE THREAD

**Issue by davej** [alexanderGugel/ied#76]
To be compatible with npm then `optionalDependencies` should be installed just like dependencies the only difference is that if there is a failure then install doesn't fail and continues regardless.

**Comment by alexanderGugel** [comment]
This might be a bit hard. Want to give it a go?

**Comment by davej** [comment]
Does `ied` currently build modules? I'm unclear of the currently supported functionality.

**Comment by rstacruz** [comment]
ied doesn't support it at the moment.

**Comment by alexanderGugel** [comment]
* `optionalDependencies` are being treated just like normal `dependencies`. This will stay like that in the forseeable future.
* lifecycle scripts (= "building modules") are currently opt-in via the the `--build` flag due to security concerns
