### ISSUE TITLE
Do consider a name change

### ISSUE THREAD

**Issue by alanhogan** [alexanderGugel/ied#78]
Currently the only question in the FAQ:

> **What does ied stand for?**
>
> Nothing in particular. …

But IED does mean something: Improvised Explosive Device, or basically the roadside bombs insurgents in e.g. Iraq and Afghanistan have used to maim and kill Western soldiers.

While this connotation will be somewhat humorous if and when an ied install fails (blowing up), overall it’s a sober one. I do personally know a programmer who was previously an Army soldier and who has suffered permanent injuries due to an IED. I can’t imagine he would love typing `ied` into his terminal multiple times a day.

I dunno. Maybe I’m being overly sensitive (probably!), but I wanted to at least voice this concern.

**Comment by brianreavis** [comment]
Context: this has been talked about at length and seems stalled: #27, #14, #29, **#45**, [HN](https://news.ycombinator.com/item?id=10571065) (all closed)

**Comment by Hunter-Github** [comment]
+1 on name change.

**Comment by Vanuan** [comment]
Expect a fork with a better name :)

**Comment by conatus** [comment]
I also think it would be better with a better name for the above reasons. My colleague propose `nom` as a lighter and funny alternative.

**Comment by nowtvicebergteam** [comment]
I think ied is a great name.

**Comment by aaronshaf** [comment]
`nom` was such a promising name :)

**Comment by dustyjewett** [comment]
Man names project IED... and it blows up in his face.

No idea why this hasn't changed yet... Maybe the controversy is worth it? But right now, there are more people commenting about the name than about anything else...

**Comment by alexanderGugel** [comment]
@dustyjewett I appreciate your opinion and analysis.

**Comment by schmod** [comment]
+1 -- the name is tasteless and undermines an otherwise-promising project.
