### ISSUE TITLE
How to uninstall/remove an installed package?

### ISSUE THREAD

**Issue by aztack** [alexanderGugel/ied#92]
I installed gulp-sass with ied, but failed to rebuild node-sass. Now I want to remove gulp-sass completely. Is there a command for doing that? Thanks.

**Comment by just-boris** [comment]
you can remove `./node_folders/gulp-sass`. Then you can try to install it again.

But be aware that you can't mix node_modules installed with NPM and IED in the same directory. So the most reliable way is removing entire `node_modules` dir and start a new installation from the scratch.

**Comment by alexanderGugel** [comment]
Removing packages just got easier. ied now traverses the entire dependency graph and detects removed sub-dependencies. `rm -rf node_modules/some-package` will work as a dream.

BTW: If you want to rebuild your dependencies, you probably want to use `ied i --build`.
